/******************************************************************************************************
 * Copyright (c) 2017 - 2025 SiliconWorks LIMITED
 *
 * file : param_configset_algorithm_mode_mpp.h
 * created on : 29. 12. 2020
 * Author : mhjang
 *
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * - Redistributions of source code must retain the above copyright
 *	 notice, this list of conditions and the following disclaimer.
 *	 - Redistributions in binary form must reproduce the above copyright
 *	 notice, this list of conditions and the following disclaimer in the
 *	 documentation and/or other materials provided with the distribution.
 * - Neither the name of SiW nor the names of its contributors may be used
 *	 to endorse or promote products derived from this software without
 *	 specific prior written permission.
 * *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDERS AND CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************************************/

#ifndef _PARAM_CONFIGSET_ALGORITHM_MODE_MPP_H_
#define _PARAM_CONFIGSET_ALGORITHM_MODE_MPP_H_


#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_cNormalizeDelta						(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_ucDiscardFrameNum					(7)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_ucInitialFrameNum					(7)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_usIIRCoef							(90)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sBlockPosThd							(20)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sBlockNegThd							(-20)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sAccumPosSumThd						(10)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sAccumNegSumThd						(-10)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sIdle_BlockPosThd					(60)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sIdle_BlockNegThd					(-60)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sIdle_SeedThd						(80)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sIdle_PosTotalSumThd					(200)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sIdle_NegTotalSumThd					(-200)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sLocalIdle_BlockPosThd				(80)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sLocalIdle_BlockNegThd				(-80)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sLocalIdle_PosTotalSumThd			(150)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sLocalIdle_NegTotalSumThd			(-150)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sS3_BlockPosThd						(60)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sS3_BlockNegThd						(-60)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sS3_PosTotalSumThd					(300)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_sS3_NegTotalSumThd					(-300)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_iRecalCond1_PosSum_Thd				(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_iRecalCond1_AccSum_Thd				(-1000)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_iRecalCond2_AccSum_Thd				(-650)//(-500)//(-200)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_ucRecalCond1_WaitCnt					(2)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_ucRecalCond2_WaitCnt					(2)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bFullModeReBaseCheckOff				(1)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bLocalModeReBaseCheckOff				(0)
#define	PARAMSET_NORMAL_MODE_ALGO_BaseLine_sFullLcoalChangeMinTh				(-30)
#define	PARAMSET_NORMAL_MODE_ALGO_BaseLine_cFullLcoalChangeMinThOffset			(-10)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_usMS_ContactTh_LocalMode				(100)//(150)
#define	PARAMSET_NORMAL_MODE_ALGO_BaseLine_usMS_ContactTh_HoverMode				(300)//(10)//(650)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_b2MUX_SUM_LocalSearchMode			(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_b2MUX_SUM_LocalMode					(NO)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bPen_2BASE							(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_cFingerAreaPenDeltaDelete			(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_cFingerAreaPenDeltaNoAcc				(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bFingerBaseTracking					(1)//(0)//(0)//(1)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_ucPP_MUX_Select						(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bDspA_Finger_CalculateDelta			(1)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bDspA_LocalMode_PenPhase				(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bDspA_LocalMode_CalculateDelta		(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bDspA_SearchMode_PenPhase			(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bDspA_SearchMode_CalculateDelta		(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_bFullFingerBaseTracking				(0)
#define PARAMSET_NORMAL_MODE_ALGO_BaseLine_ucLocalNormalizeMaxOffset			(0)//(10)//(15)//(30)

#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_cLineFilter						(2)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_sLineFilterUpLimit              (100)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_sLineFilterLowLimit             (-100)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucLineFilterColOffset           (4)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucLineFilterRepeatTH			(0)//(20)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_cLineFilterMinTH				(-20)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucMinDeltaTh					(20)//(20) //0
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_cLineFilter_Pen					(0)//(1)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucLocalSearchModeLineFilter		(0)//(1)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_bRingRawLineFilter	            (0)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_sLineFilterUpLimit_Pen			(10)	
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_sLineFilterLowLimit_Pen			(-10)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_sLineFilterUpLimit_Idle			(100)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_sLineFilterLowLimit_Idle		(-100)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucRingDeltaIIR_Coef				(150)//(120)//(60) 
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_sFingerAreaLineFilterLimit		(0)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucFingerAreaLineFilterOffset	(0)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucHighHoverDeltaIIR_Coef		(150)//(100)
#define PARAMSET_NORMAL_MODE_ALGO_SensingFilter_ucContactDeltaIIR_Coef			(150)

#define PARAMSET_NORMAL_MODE_ALGO_Label_usSeedBase								(20)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucSeedSlope								(5)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLabelNoiseThd							(8)
#define PARAMSET_NORMAL_MODE_ALGO_Label_bExpand									(YES)
#define PARAMSET_NORMAL_MODE_ALGO_Label_bSplitSearchDirc_4_On					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usSmallNodeCnt							(13)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usMediumNodeCnt							(42)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucMergeSmallThdPer						(75)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucMergeMediumThdPer						(80)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucMergeSmallDiagThdPer					(70)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucMergeMediumDiagThdPer					(80)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usLocalSeedBase							(12)//(20)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalSeedSlope						(5)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usLocalSmallNodeCnt						(12)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usLocalMediumNodeCnt					(32)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalMergeSmallThdPer					(85)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalMergeMediumThdPer				(70)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usLocalSeedBase_Ring					(10)
#define	PARAMSET_NORMAL_MODE_ALGO_Label_ucRingSeedBase_Acoef					(15)
#define	PARAMSET_NORMAL_MODE_ALGO_Label_ucRingSeedBase_Fcoef					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalPenDetectTH1						(18)//(25)//(40)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalPenDetectTH2						(75)//(90)//(160)
#if (USED_PEN_PROTOCOL & PEN_PROTOCOL_MULTI_PROTOCOL_OPERATION)
	#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalPenDetectTH1_Offset			(5)
	#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalPenDetectTH2_Offset			(20)
#else /* (USED_PEN_PROTOCOL & PEN_PROTOCOL_MULTI_PROTOCOL_OPERATION) */
	#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalPenDetectTH1_Offset			(3)//(5)//(15)
	#define PARAMSET_NORMAL_MODE_ALGO_Label_ucLocalPenDetectTH2_Offset			(10)//(20)//(30)
#endif /* (USED_PEN_PROTOCOL & PEN_PROTOCOL_MULTI_PROTOCOL_OPERATION) */
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucHoverInCheckFrm						(15)//(11)//(35)//(8)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucHoverOutCheckFrm						(17)//(12)//(37)//(8)
#define PARAMSET_NORMAL_MODE_ALGO_Label_ucHoverOutOffset						(0)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usLabelPeakValleyDiffTh					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usLabelPeakDiffTh						(0)
#define PARAMSET_NORMAL_MODE_ALGO_Label_usMergeLabelSizeTh						(0)

// Coord
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usDistThdMovingToStationary				(32)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usDistThdStationaryToMoving				(80)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_lMoveSmoothingLevel						(8)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucVectorPredictionCoef					(100) // 50 ~ 150
#if USED_ONLY_LOCAL_MODE
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucLocalFingerInterpolation_On			(4)
#else /* USED_ONLY_LOCAL_MODE */
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucLocalFingerInterpolation_On			(0)
#endif /* USED_ONLY_LOCAL_MODE */
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucFullFingerInterpolation_On			(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sInterpolationWeight					(128)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucFirstMoveEventTHD						(5)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucMoveEventTHD							(20)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFingerGlobalCoordiXResolutionOffset	(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFingerGlobalCoordiYResolutionOffset	(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFingerGlobalCoordiOffsetX				(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFingerGlobalCoordiOffsetY				(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucSmoothPastOrgInter					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_cDisSmoothOffset						(1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bFingerMeanSmoothing					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucWinCertAssistance 					(0)		//0 : Off, 1 : LGD MNT 27", 2 : LGD Kiosk
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucTouchCountMax							(3)		//LGD MNT 27" : 3, LGD Kiosk 43",55" : 30
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucMaxExtendFrameNum						(10)	//LGD MNT 27" : 10, LGD Kiosk 43", 55" : 100
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usFirstDrawingThd		 				(128)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucFirstDrawingCellCnt					(15)

// CoordTracking
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucDynamicTrackingDistanceMode			(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucFastDrawingMode						(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usMoveDistanceThd						(3)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usFirstMoveDistanceThd					(7)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_lLargeTouchOnThd						(180)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucLargeTouchOnDebCnt					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_lMediumTouchOnThd						(120)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucMediumTouchOnDebCnt					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_lSmallTouchOnThd						(30)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucSmallTouchOnDebCnt					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bEdgeDebCntUp							(1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFirstTouchOnMaxCellVal					(40)//(50)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_lTouchOffThd							(25)//(40)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucMultifingerFirstTouchThDownOffset		(10)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usCenterMatchDistanceThd				(13)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFirstTouchEnable1Touch					(0)	    //Enable First touch
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFirstTouchEnable2Touch					(40)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFirstTouchEnable3Touch					(35)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFirstTouchEnable4Touch					(35)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sFirstTouchEnable5Touch					(35)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucDebCntInner							(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucDebCntEdge			 				(0)

// CoordEdge
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bExpectClipping_Finger_On				(1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_cEdgeSmoothing_Finger_On				(40)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bRemoveEdge								(1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usRemoveEdgeXdistThd					(65)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usRemoveEdgeYdistThd					(65)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bUsetRealPastSentPos1					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucRemoveEdgeVer							(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usPostProcessEdgeTH						(UNIT_DIST << 1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucPostProcessDisTH						(UNIT_DIST >> 3)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucPostProcessExpendDiv					(1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_cPostProcessEndMargin					(55)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bPostProcessInterpolationMode			(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usOutInDrawEdgeTh						(0)//(1024)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucOutInDrawDisTh						(70)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bUseNewCippingCond						(1)

// EdgeExpand
#define PARAMSET_NORMAL_MODE_ALGO_Coord_bUseMultiEdgeCoef						(1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usSmallTouchMaxDeltaThd					(90)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucSmallTouchCellCntThd					(15)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucSmallTouchHeightThd					(5)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucSmallTouchWidthThd					(5)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucLeftEdgeExpand						(100)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucRightEdgeExpand						(100)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucTopEdgeExpand							(100)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucBottomEdgeExpand						(100)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucLeftEdgeExpand_small					(73)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucRightEdgeExpand_small					(73)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucTopEdgeExpand_small					(73)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucBottomEdgeExpand_small				(73)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucLeftEdgeExpand_medium					(75)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucRightEdgeExpand_medium				(75)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucTopEdgeExpand_medium					(75)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucBottomEdgeExpand_medium				(75)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sXExpandStartOffset						(256)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_sYExpandStartOffset						(256)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usLabelEdgeExpandMode					(1)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usLeftEdgeExpand_Offset					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usRightEdgeExpand_Offset				(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usTopEdgeExpand_Offset					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBottomEdgeExpand_Offset				(0)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usLeftEdgeExpand_Scale					(128)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usRightEdgeExpand_Scale					(128)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usTopEdgeExpand_Scale					(128)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBottomEdgeExpand_Scale				(128)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usLeftEdgeExpand_MaxD					(600)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usRightEdgeExpand_MaxD					(600)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usTopEdgeExpand_MaxD					(600)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBottomEdgeExpand_MaxD					(600)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeExpandParam1				(9000)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeExpandParam2				(70)//(80)
#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeExpandParam3				(2000)
#if (USED_PEN_PROTOCOL == PEN_PROTOCOL_MS_PEN) && (CUSTOMER == MODEL_DEF_FHD_92503B)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucEdgeReportDelayCnt					(3)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTest_MoveEventTHD_X	(196)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTest_MoveEventTHD_Y	(365)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingTop		(580)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingBottom		(580)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingLeft		(320)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingRight		(320)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_bFingerCornerTestClippingOn			(1)
#else
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_ucEdgeReportDelayCnt					(0)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTest_MoveEventTHD_X	(0)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTest_MoveEventTHD_Y	(0)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingTop		(0)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingBottom		(0)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingLeft		(0)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_usBigFingerEdgeTestClippingRight		(0)
	#define PARAMSET_NORMAL_MODE_ALGO_Coord_bFingerCornerTestClippingOn			(0)
#endif

#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucTipRangeExtend_On					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_bExpectClipping_Pen_On				(YES)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucCompenCoefA						(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucCompenCoefB						(5)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucHoverCompenCoefA					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucHoverCompenCoefB					(5)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_bCompenEdgeOn						(NO)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucPenPostProcessEdgeTH				(9)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucPenPostProcessDisTH				(16)//(32)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucPenPostProcessExpendDiv			(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_cPenPostProcessEndMargin				(50)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_cHoverSmoothOffset					(0)//(-127)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_bFullFingerOn						(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_sPenGlobalCoordiXResolutionOffset	(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_sPenGlobalCoordiYResolutionOffset	(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_sPenGlobalCoordiOffsetX				(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_sPenGlobalCoordiOffsetY				(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_sXExpandStartOffset					(255)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_sYExpandStartOffset					(255)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucLeftEdgeExpand_local				(70)//(75)//(90)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucRightEdgeExpand_local				(70)//(74)//(90)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucTopEdgeExpand_local				(70)//(74)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucBottomEdgeExpand_local				(70)//(74)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_uclatency_up_dis_condition			(0)//(120)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_uclatency_up_cnt_condition			(10)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_clatency_up_dis_offset				(30)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ideal_inter_dis						(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ideal_inter_mv						(2)
#if (IdealInterOnlyCorner == YES)
	#define PARAMSET_NORMAL_MODE_1_ALGO_PenCoord_us_ideal_inter_only_corner		(0)//(512)
#endif	
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_uc_connect_count						(4)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucMarkBoundaryNum					(1)//(2)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucPenEdgeDebCnt                      (0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_usLongDisPointExceptionTH			(1024)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_usPannelOutSideHoverExceptionTH	(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_usPannelOutSideContactExceptionTH	(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucPannelOutSideHoverExceptionEdgeDis	(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucPannelOutSideContactExceptionEdgeDis	(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucPannelOutSideContactExceptionPreDis	(0)
#if (OUT_IN_DRAWING == YES)
	#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_usOutInBoundTh	(512)
	#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucOutInDisTh	(16)
#endif
#if (HIGH_HOVER_JITTER_REDUCE == YES)
	#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_sHighHoverJitterReduceDisScale			(200)
	#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_ucHighHoverJitterReduceSmoothOffset		(120)
#endif
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_bUseNewCippingCond_Pen				(1)		// If you use Remove Edge, bUseNewCippingCond_Pen = 1
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_bRemoveEdge							(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_usRemoveEdgeXdistThd					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_usRemoveEdgeYdistThd					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_bUsetRealPastSentPos1				(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenCoord_usEndCoordMargin						(0)

#define	PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucMS_RingMode							(0)//(2)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bTiltCalOnlyContact					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_cHoverOverShiftRingOffset				(0)//(-1)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucHoverDeltaMul						(0)//(20)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bTiltCalUsingTipOrg					(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bRingRangeExtend_On					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltSubMaxDelta						(100)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDivMin							(1.5*UNIT_DIST)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDivMax							(4*UNIT_DIST)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucRingCompenCoefA						(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucRingCompenCoefB                     (0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucRingCoordSmoothCoef					(6)//(4)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucCoordiShiftX_WithTilt				(12) //(6)//(8)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucCoordiShiftY_WithTilt	            (12) //(6)//(8)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucCoordiShiftEdgeOn                   (1)//(0)//(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucCoordiShiftWithTilt_RingTH          (0)//(20)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucCoordiShiftWithTiltCompenTH         (0)//(200)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucTiltL                               (59)//(53)//(55)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucTiltAdjustEn						(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltChangeLimitFilter               (0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucTiltSmoothingFilterCoef             (31)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucHalfCoefSmoothFrm					(3)//(2)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucHalfCoef							(16)//(1)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucHighDelta_TiltSmooth_change_Th		(35)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_cHighDelta_TiltSmooth_change_offset	(-7)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_cHoverMode_TiltSmooth_change_offset	(-7)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTilt_Change_TH_Reverse				(300)//(500)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTilt_Change_TH_Right				(120)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bRingCoordiReport						(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucRingMarkBoundaryNum					(0)	
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bTiltBasedRingDelta					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bTiltDirecLimitFilter					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_ucTiltDeltaLimitFilter				(2)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDeltaLimit_10_TH				(0)//(200)//(170)
#if (TiltDeltaLimit_ADD == YES)
	#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDeltaLimit_40_TH				(440)
	#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDeltaLimit_50_TH				(620)
#endif
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDeltaLimit_55_TH				(0)//(800)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDeltaLimit_60_TH				(350)//(950)//(1100)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usTiltDeltaLimit_65_TH				(0)//(1150)//(1300)//(800)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bTiltMedianFilter						(0)//(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bRingBaseTracking						(0)//(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bTiltRowIndexChange					(1)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usReleaseLastContact3x3Frm			(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_usUseLastContact3x3Th					(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenTilt_bArcSinLookUp_1						(3)//(1)

#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucAdaptive_contact_th				(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucPenDataLocalTHD						(60)//(40)//(10)//(50)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucPenDataHoverTHD						(110)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_sPenDataHoverButtonTHD				(210)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_usPenDataHighHoverButtonRejectTHD		(0)//(700)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucPenDataHighHoverButton1ReliableCnt (5)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucPenDataHighHoverButton2ReliableCnt (5)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucPenDataHighHoverButtonAdopThOffset (50)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucPenDataHighHoverButtonIIRcoef		(200)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucForcePenContact_NUM					(1)//(5)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucAbnormalContactRemoveDeltaTH1		(0)//(17)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucAbnormalContactRemoveDeltaTH2		(0)//(30)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucAbnormalContactRemovePressureTH1	(0)//(35)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucAbnormalContactRemovePressureTH2	(0)//(70)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucSEN_CONT_CNT						(2)//(5)//(10)//(20)
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucKeepProtocolNum						(16)
#if USED_PEN_PRESSURE_BRUSH_LEVEL_CTRL
	#define PARAMSET_NORMAL_MODE_ALGO_PenData_bOrgPressureInterpolation			(1)
	#define PARAMSET_NORMAL_MODE_ALGO_PenData_ulPressureLevelIIRPrevCoefTHD		(8) // 1~15 Set
	#define PARAMSET_NORMAL_MODE_ALGO_PenData_ulPressureChangeRatioTHD			(55) // 0~100 Max 100
	#define PARAMSET_NORMAL_MODE_ALGO_PenData_bUsedBrushFinishTip					(1)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenData_bBrushFinishPressure1Report			(0)
#endif /* USED_PEN_PRESSURE_BRUSH_LEVEL_CTRL */
#define PARAMSET_NORMAL_MODE_ALGO_PenData_ucPenContactReliableCnt				(1)

#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_th							(-100)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_mul							(0)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_SR							(3)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_th						(-100)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_mul						(0)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_SR						(3)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_th							(-100)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_mul						(0)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_SR							(3)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_th						(-100)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_mul						(0)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_SR						(3)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_hover_th					(450)//(550)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_hover_mul					(33)//(36)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_hover_SR					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_hover_th					(450)//(550)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_hover_mul				(33)//(36)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_hover_SR					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_hover_th					(450)//(550)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_hover_mul					(33)//(36)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_hover_SR					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_hover_th					(450)//(550)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_hover_mul					(33)//(36)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_hover_SR					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_ring_th						(500)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_ring_mul					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_top_ring_SR						(2)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_ring_th					(500)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_ring_mul					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_bottom_ring_SR					(2)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_ring_th					(550)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_ring_mul					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_left_ring_SR					(2)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_ring_th					(500)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_ring_mul					(5)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_right_ring_SR					(2)
#define PARAMSET_NORMAL_MODE_ALGO_EdgePenSetVal_chover_mul_button1_offset		(4)
 
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_c_edge_smooth_offset_hover					(127)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_c_edge_smooth_offset_contact  				(16)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_uc_global_smooth_dis_condition_contact		(16)//(32)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_c_global_smooth_offset_contact				(16)//(64)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_us_corner_smooth_delta_condition_hover		(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_c_corner_smooth_offset_hover				(127)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_uc_edge_smooth_dis_condition_contact		(64)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_uc_global_smooth_delta_condition_hover		(150)//(255)//(150)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_uc_global_smooth_dis_condition_hover		(255)//(128)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_c_global_smooth_offset_hover				(-127)//(-16)
#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_usEdge_Range								(256)		
#if (CornerSmoothContact == YES)
	#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_usCornerSmoothContact_CornerRange		(0)//(255)
	#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_ucCornerSmoothContact_DisCondition		(0)//(16)
	#define PARAMSET_NORMAL_MODE_ALGO_PenDisBaseSmoothSetVal_cCornerSmoothContact_SmoothOffset		(0)//(80)
#endif

#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_th0							(0)//(7)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_mul0					(31)//(22)//(24)//(21)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_SR0						(5)//(5)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_mul1					(0)//(9)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_SR1						(0)//(0)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_mul0					(31)//(24)//(21)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_SR0					(5)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_mul1					(0)//(9)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_SR1					(0)//(0)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_mul0					(33)//(22)//(24)//(23)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_SR0					(5)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_mul1					(0)//(9)//(8)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_SR1					(0)//(0)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_mul0					(33)//(22)//(25)//(23)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_SR0					(5)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_mul1					(0)//(9)//(8)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_SR1					(0)//(0)//(0)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_max_sum					(65)//(170)//(220)//(170)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_max_sum				(70)//(170)//(220)//(170)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_max_sum				(65)//(170)//(210)//(170)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_max_sum				(63)//(170)//(200)//(170)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_max_sum_corner			(30)//(37)//(100)//(80)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_max_sum_corner		(25)//(37)//(100)//(80)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_max_sum_corner			(30)//(37)//(100)//(80)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_max_sum_corner		(28)//(37)//(100)//(80)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_max_sum_hover			(1500)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_max_sum_hover		(1500)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_max_sum_hover			(1500)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_max_sum_hover			(1500)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_hover_div			(4)
#if (PEN_CORNER_EXPEND_ADD == YES)
	#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_top_max_sum_corner1		  (80)//(120)
	#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_bottom_max_sum_corner1    (80)//(100)
	#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_left_max_sum_corner1      (80)//(120)
	#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_right_max_sum_corner1     (80)//(110)
	#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltY_LT   (0)//(150)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltY_RT   (0)//(150)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltY_LB   (0)//(150)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltY_RB   (0)//(150)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltX_LT   (0)//(150)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltX_RT   (0)//(150)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltX_LB   (0)//(150)
	#define	PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_max_sum_corner_TiltX_RB   (0)//(150)
#endif
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_ucUsePerMaxSum				(22)
#define PARAMSET_NORMAL_MODE_ALGO_PenParaEdgeSetVal_ulExtStrengthInit			(270)

#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucNoiseDetectionMode					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucDiscardFrameNum						(5)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucCellCntThd							(1)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucHoppingThd							(17)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucNoiseThd								(7)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_usRawDataThd							(100)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_sDeltaDataThd							(-20)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucTouchOffCntThd						(10)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_bPenNoiseReductionOff					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucPenFingerSameLineNoiseSize			(5)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucHoverNoiseRejectTH					(2)//(2)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucHoverNoiseRejectFrm					(1)//(2)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucSearchNoiseRejectTH					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucSearchNoiseRejectFrm					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_cAdaptorNoiseTH							(-50)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucAdaptorNoiseContiNum					(10)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_cAdaptorNoiseTH_SearchHover				(0)//(-25)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucAdaptorNoiseContiNum_SearchHover		(0)//(5)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_bPenPosSymbolRepeatCheck				(1)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucCPITestOn								(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucErrorFrameProcess						(0)
#define	PARAMSET_NORMAL_MODE_ALGO_Noise_ucHoppingMoveDistanceThd				(4)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucNoiseDetectMaxType					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_bInitAddHoppingThd						(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_bHoppingConnectPenContact				(0)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucNoiseStartThd							(5)
#define PARAMSET_NORMAL_MODE_ALGO_Noise_ucNoiseStartCntThd						(2)

#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalmDetectionOn						(3)//(2)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_usPalmLevel								(25)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalm_PALM_CONNECT_DIST					(5)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalm_PALM_REGION_UPDATE_PERIOD			(10)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalm_TOUCHDOWNFRAMEMAX					(5)//(2)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalm_TOUCHDOWNSLOPETHRESHOLD			(170)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalm_IGNOREFRAMENUM					(0)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalm_KEEPPALMREGIONFRAME				(30)//(50)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalmDrawingOn							(0)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_bPalm_WholeTouchRemove					(NO)
#if (PENnPalm_PalmAreaMaintain_EN == YES)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_bPalm_bPenPalmDetection					(YES) // Sony Pen & Palm Algorithm On / Off
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPenPalm_PALM_CONNECT_DIST				(8)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPenPalm_KEEPPALMREGIONFRAME			(200)//(120)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPen_KEEPFRAME							(200)//(120)
#define	PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalmRelaseFrame						(100)//(30)
#endif /* (PENnPalm_PalmAreaMaintain_EN == YES) */
#define PARAMSET_NORMAL_MODE_ALGO_Palm_usPalmCandiStdTh							(500)//(430)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalmCandiShapeMatchingTh				(0)	
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalmCandiDeltaTh						(20)
#define PARAMSET_NORMAL_MODE_ALGO_Palm_ucPalmNonReleaseFingerTouchEn			(25)

#define PARAMSET_NORMAL_MODE_ALGO_ucOvrShift									(3)
#define PARAMSET_NORMAL_MODE_ALGO_ucIdleOvrShift								(2)
#define PARAMSET_NORMAL_MODE_ALGO_ucLocalOvrShift								(3)
#define PARAMSET_NORMAL_MODE_ALGO_ucLocalIdleOvrShift							(2)
#define PARAMSET_NORMAL_MODE_ALGO_ucLocalOvrShift_Ring							(1)


#endif /* _PARAM_CONFIGSET_ALGORITHM_MODE_MPP_H_ */
