/****************************************************************************************************/ /**
 * Copyright (c) 2017 - 2025 SiliconWorks LIMITED
 *
 * file : param_configset_roic.h
 * created on : 3. 4. 2019
 * Author : mhjang
 *
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * - Redistributions of source code must retain the above copyright
 *	 notice, this list of conditions and the following disclaimer.
 *	 - Redistributions in binary form must reproduce the above copyright
 *	 notice, this list of conditions and the following disclaimer in the
 *	 documentation and/or other materials provided with the distribution.
 * - Neither the name of SiW nor the names of its contributors may be used
 *	 to endorse or promote products derived from this software without
 *	 specific prior written permission.
 * *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDERS AND CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************************************/

#ifndef _PARAM_CONFIGSET_ROIC_H_
#define _PARAM_CONFIGSET_ROIC_H_


/************************************************************************************************************/
/*											WGP ROIC Setting												*/
/************************************************************************************************************/
/*
 * Finger Sensing
 */
#define PARAMSET_ROIC_PWM_CTL_pwm_pdrv_num					(0)
#define PARAMSET_ROIC_PWM_CTL_pwm_act_num					(5)//(11)//(5)

#define PARAMSET_ROIC_PWM_CTL_pwm_mgap_num					(1)
#define PARAMSET_ROIC_PWM_CTL_pwm_dum_num					(8)//(2)
#define PARAMSET_ROIC_PWM_CTL_pwm_set_num					(1)

#define PARAMSET_ROIC_CFGR_FG_LHB_CFG_lhbmuxnum				(2)	/* N+1 */

/*
 * Pen Tilt Sensing
 */
#define PARAMSET_ROIC_PWM_POS_CTL_pwm_pdrv_num				(0)
#define PARAMSET_ROIC_PWM_POS_CTL_pwm_act_num				(9)
#define PARAMSET_ROIC_PWM_POS_CTL_pwm_mgap_num				(1)
#define PARAMSET_ROIC_PWM_POS_CTL_pwm_dum_num				(8)
#define PARAMSET_ROIC_PWM_POS_CTL_pwm_set_num				(1)

#define PARAMSET_ROIC_CFGR_PP_LHB_CFG_lhbmuxnum				(1)	/* N+1 */
#define PARAMSET_ROIC_CFGR_PP_LHB_CFG_pp_mux_cfg0			(0)
#define PARAMSET_ROIC_CFGR_PP_LHB_CFG_pp_mux_cfg1			(0)
#define PARAMSET_ROIC_CFGR_PP_LHB_CFG_pp_mux_cfg2			(0)
#define PARAMSET_ROIC_CFGR_PP_LHB_CFG_pp_mux_cfg3			(0)

/*
 * Pen Position & Data Sensing
 */
#define PARAMSET_ROIC_PWM_DATA_CTL_pwm_pdrv_num				(0)
#define PARAMSET_ROIC_PWM_DATA_CTL_pwm_act_num				(4)
#define PARAMSET_ROIC_PWM_DATA_CTL_pwm_mgap_num				(0)
#if USED_TOUCH_WGP_PREDRV_MUX_SENSING
	#define PARAMSET_ROIC_PWM_DATA_CTL_pwm_dum_num				(3)
#else
	#define PARAMSET_ROIC_PWM_DATA_CTL_pwm_dum_num				(8)
#endif
#define PARAMSET_ROIC_PWM_DATA_CTL_pwm_set_num				(1)

#define PARAMSET_ROIC_PWM_IDLE_CTL_pwm_pdrv_num				(0)
#define PARAMSET_ROIC_PWM_IDLE_CTL_pwm_act_num				(5)
#define PARAMSET_ROIC_PWM_IDLE_CTL_pwm_mgap_num				(1)
#define PARAMSET_ROIC_PWM_IDLE_CTL_pwm_dum_num				(8)
#define PARAMSET_ROIC_PWM_IDLE_CTL_pwm_set_num				(1)

#if USED_TOUCH_WGP_PREDRV_MUX_SENSING
	#define PARAMSET_ROIC_CFGR_PP_LHB_CFG_pd_tmuxnum			(7)	/* Local Index Setting Continuous Set Value N+1 */
	#define PARAMSET_ROIC_CFGR_PD_LHB_CFG_lhbmuxnum				(7) /* Mux Sensing Num in 1 LHB N+1 */
#else
	#define PARAMSET_ROIC_CFGR_PP_LHB_CFG_pd_tmuxnum			(6)	/* Local Index Setting Continuous Set Value N+1 */
	#define PARAMSET_ROIC_CFGR_PD_LHB_CFG_lhbmuxnum				(6) /* Mux Sensing Num in 1 LHB N+1 */
#endif
#define PARAMSET_ROIC_CFGR_PD_LHB_CFG_pd_mux_cfg0			(0)
#define PARAMSET_ROIC_CFGR_PD_LHB_CFG_pd_mux_cfg1			(0)
#define PARAMSET_ROIC_CFGR_PD_LHB_CFG_pd_mux_cfg2			(0)
#define PARAMSET_ROIC_CFGR_PD_LHB_CFG_pd_mux_cfg3			(0)
#define PARAMSET_ROIC_CFGR_PD_LHB_CFG_pd_tsync_muxnum		(0)

#define PARAMSET_ROIC_CFGR_LHB_CFG_tsync_num				(8)

#define PARAMSET_ROIC_CFGR_LHB_MCFG_1LHB_FULL				(1)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_2LHB_FULL				(0)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_3LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_4LHB_FULL				(0)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_5LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_6LHB_FULL				(0)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_7LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_8LHB_FULL				(0)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_9LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_10LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_11LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_12LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_13LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_14LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_15LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_16LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_17LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_18LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_19LHB_FULL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_20LHB_FULL				(6)

#define PARAMSET_ROIC_CFGR_LHB_MCFG_1LHB_LOCAL				(1)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_2LHB_LOCAL				(3)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_3LHB_LOCAL				(2)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_4LHB_LOCAL				(3)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_5LHB_LOCAL				(0)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_6LHB_LOCAL				(3)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_7LHB_LOCAL				(0)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_8LHB_LOCAL				(3)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_9LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_10LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_11LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_12LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_13LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_14LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_15LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_16LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_17LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_18LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_19LHB_LOCAL				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_20LHB_LOCAL				(6)

#define PARAMSET_ROIC_CFGR_LHB_MCFG_1LHB_IDLE				(1)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_2LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_3LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_4LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_5LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_6LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_7LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_8LHB_IDLE				(4)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_9LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_10LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_11LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_12LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_13LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_14LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_15LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_16LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_17LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_18LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_19LHB_IDLE				(6)
#define PARAMSET_ROIC_CFGR_LHB_MCFG_20LHB_IDLE				(6)

#define PARAMSET_ROIC_CFGR_SENSE_CTRL_lv_ssu_bcon			(1)//(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_lv_ssu_bcons			(1)//(2)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_hv_ssu_bcon			(0)//(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_pen_dc_md				(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_pen_dc_md_stuck		(0)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_integ_half_f			(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_integ_half_p			(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_integ_half_comp		(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_pre_gc_f				(3)//(2)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_pre_gc_p				(3)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_pre_gc_comp			(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_int_gc_f				(3)//(2)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_int_gc_p				(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_int_gc_comp			(1)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_powsel				(0)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_pre_bs_lp				(0)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_int_bs_lp				(0)
#define PARAMSET_ROIC_CFGR_SENSE_CTRL_tm_ssu_pen			(0)

#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_adc_bcon			(1)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_adc_stc_insel		(0)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_adc_dsf			(1)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_adc_ref_sel		(0)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_int_ref			(4)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_sha_ref			(4)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_sha_bs_lp			(0)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_ref_res_sel		(0)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_lv_comp_bcon		(0)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_comp_hys_ctrl		(0)
#define PARAMSET_ROIC_CFGR_COMP_ADC_CTRL_tm_comp			(0)

#define PARAMSET_ROIC_CFGR_PWM_PRD_pwm_prd1					(48)
#define PARAMSET_ROIC_CFGR_PWM_PRD_pwm_prd2					(48)

#define PARAMSET_ROIC_CFGR_RSTP_NUM1_rstp_num1				(15)
#define PARAMSET_ROIC_CFGR_RSTP_NUM1_rstp_num2				(3)

#define PARAMSET_ROIC_CFGR_PHTCR_NUM1_phtcr_num1_1			(44)
#define PARAMSET_ROIC_CFGR_PHTCR_NUM1_phtcr_num1_2			(44)

#define PARAMSET_ROIC_CFGR_PHTCR_NUM2_phtcr_num2_1			(30)
#define PARAMSET_ROIC_CFGR_PHTCR_NUM2_phtcr_num2_2			(30)

#define PARAMSET_ROIC_CFGR_VCR_NUM1_vcr_num1_1				(60)
#define PARAMSET_ROIC_CFGR_VCR_NUM1_vcr_num1_2				(40)

#define PARAMSET_ROIC_CFGR_RSTI_NUM1_rsti_num1				(15)

#define PARAMSET_ROIC_CFGR_RSTI_NUM2_rsti_num2_1			(3)
#define PARAMSET_ROIC_CFGR_RSTI_NUM2_rsti_num2_2			(40)

#define PARAMSET_ROIC_CFGR_PHTH0_NUM1_phth0_num1_1			(16)
#define PARAMSET_ROIC_CFGR_PHTH0_NUM1_phth0_num1_2			(16)

#define PARAMSET_ROIC_CFGR_PHTH1_NUM1_phth1_num1_1			(15)
#define PARAMSET_ROIC_CFGR_PHTH1_NUM1_phth1_num1_2			(15)

#define PARAMSET_ROIC_CFGR_PHTH_NUM2_phth0_num2				(2)
#define PARAMSET_ROIC_CFGR_PHTH_NUM2_phth1_num2				(30)

#define PARAMSET_ROIC_CFGR_PHT_NUM1_pht_num1				(23)
#define PARAMSET_ROIC_CFGR_PHT_NUM1_pht_num2				(18)

#if 0
#define PARAMSET_ROIC_CFGR_R0_CH_EN_ch_en_lvr				(15)
#define PARAMSET_ROIC_CFGR_R0_CH_EN_ch_en_hvr				(15)
#define PARAMSET_ROIC_CFGR_R1_CH_EN_ch_en_lvr				(15)
#define PARAMSET_ROIC_CFGR_R1_CH_EN_ch_en_hvr				(15)
#else
#define PARAMSET_ROIC_CFGR_R0_CH_EN_ch_en_lvr				(127)
#define PARAMSET_ROIC_CFGR_R0_CH_EN_ch_en_hvr				(511)
#define PARAMSET_ROIC_CFGR_R1_CH_EN_ch_en_lvr				(127)
#define PARAMSET_ROIC_CFGR_R1_CH_EN_ch_en_hvr				(511)
#endif

#if 1
#define PARAMSET_ROIC_CFGR_TG_STUCK_stuck_muxf_en			(0)
#define PARAMSET_ROIC_CFGR_TG_STUCK_stuck_muxs_en			(0)
#define PARAMSET_ROIC_CFGR_MUX_S_STUCK_VAL_mux_s_stuck_val	(0)
#define PARAMSET_ROIC_CFGR_MUX_F_STUCK_VAL_mux_f_stuck_val	(0)
#else
/*
 * CMUX OFF (Floating)
 */
//#define PARAMSET_ROIC_CFGR_TG_STUCK_stuck_muxf_en			(1)
//#define PARAMSET_ROIC_CFGR_TG_STUCK_stuck_muxs_en			(1)
//#define PARAMSET_ROIC_CFGR_MUX_S_STUCK_VAL_mux_s_stuck_val	(0)
//#define PARAMSET_ROIC_CFGR_MUX_F_STUCK_VAL_mux_f_stuck_val	(1)
/*
 * CMUX OFF (Vcom)
 */
#define PARAMSET_ROIC_CFGR_TG_STUCK_stuck_muxf_en			(1)
#define PARAMSET_ROIC_CFGR_TG_STUCK_stuck_muxs_en			(1)
#define PARAMSET_ROIC_CFGR_MUX_S_STUCK_VAL_mux_s_stuck_val	(0)
#define PARAMSET_ROIC_CFGR_MUX_F_STUCK_VAL_mux_f_stuck_val	(0)
#endif

#define PARAMSET_ROIC_0_R0_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_0_R0_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_0_R0_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_1_R0_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_1_R0_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_1_R0_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_2_R0_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_2_R0_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_2_R0_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_3_R0_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_3_R0_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_3_R0_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_4_R0_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_4_R0_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_4_R0_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_5_R0_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_5_R0_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_5_R0_CR_GTUNE_PenData_Global_Tune		(0)

#define PARAMSET_ROIC_0_R1_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_0_R1_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_0_R1_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_1_R1_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_1_R1_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_1_R1_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_2_R1_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_2_R1_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_2_R1_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_3_R1_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_3_R1_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_3_R1_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_4_R1_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_4_R1_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_4_R1_CR_GTUNE_PenData_Global_Tune		(0)
#define PARAMSET_ROIC_5_R1_CR_GTUNE_Finger_Global_Tune		(0)
#define PARAMSET_ROIC_5_R1_CR_GTUNE_PenPos_Global_Tune		(0)
#define PARAMSET_ROIC_5_R1_CR_GTUNE_PenData_Global_Tune		(0)


#define PARAMSET_ROIC_1stMUX_IDX							(0)
#define PARAMSET_ROIC_R0_TUNE_GROUP_cr_rg2_sel				(10)
#define PARAMSET_ROIC_R0_TUNE_GROUP_cr_rg3_sel				(4)
#define PARAMSET_ROIC_R1_TUNE_GROUP_cr_rg2_sel				(10)
#define PARAMSET_ROIC_R1_TUNE_GROUP_cr_rg3_sel				(4)
#define PARAMSET_ROIC_1stMUX_TUNE_GROUP_cr_rg2_sel			(46)
#define PARAMSET_ROIC_1stMUX_TUNE_GROUP_cr_rg3_sel			(508)
#define PARAMSET_ROIC_LastMUX_IDX							(5)
#define PARAMSET_ROIC_LastMUX_TUNE_GROUP_cr_rg2_sel			(2)
#define PARAMSET_ROIC_LastMUX_TUNE_GROUP_cr_rg3_sel			(508)


#if USED_RAWDATA_TUNE_CALIBRATION
#define PARAMSET_ROIC_0_R0_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R0_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R0_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R0_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R0_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R0_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R0_1stMux_Bottom_Line_g3			(0x0)

#define PARAMSET_ROIC_0_R0_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_2ndMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_3rdMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_4thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_4thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_4thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_4thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_4thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_4thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_4thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_4thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_4thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_4thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_4thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_4thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_4thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_4thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_4thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_4thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_4thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_4thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_5thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_5thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_5thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_5thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_5thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_5thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_5thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_5thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_5thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_5thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_5thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_5thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_5thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_5thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_5thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_5thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_5thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_5thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_6thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_6thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_6thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_6thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_6thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_6thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_6thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_6thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_6thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_6thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_6thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_6thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_6thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_6thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_6thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_6thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_6thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_6thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_7thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_7thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_7thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_7thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_7thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_7thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_7thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_7thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_7thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_7thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_7thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_7thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_7thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_7thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_7thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_7thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_7thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_7thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_8thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_8thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_8thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_8thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_8thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_8thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_8thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_8thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_8thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_8thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_8thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_8thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_8thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_8thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_8thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_8thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_8thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_8thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_9thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R0_9thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R0_9thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R0_9thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R0_9thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R0_9thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R0_9thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R0_9thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R0_9thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R0_9thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R0_9thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R0_9thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R0_9thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R0_9thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R0_9thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R0_9thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R0_9thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R0_9thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R0_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R0_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R0_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R0_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R0_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R0_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R0_LastMux_Bottom_Line_g3			(0x0)

#define PARAMSET_ROIC_0_R1_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R1_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R1_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R1_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R1_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R1_1stMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R1_1stMux_Bottom_Line_g3			(0x0)

#define PARAMSET_ROIC_0_R1_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_2ndMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_2ndMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_2ndMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_2ndMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_3rdMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_3rdMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_3rdMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_3rdMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_4thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_4thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_4thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_4thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_4thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_4thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_4thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_4thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_4thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_4thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_4thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_4thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_4thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_4thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_4thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_4thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_4thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_4thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_5thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_5thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_5thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_5thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_5thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_5thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_5thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_5thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_5thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_5thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_5thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_5thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_5thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_5thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_5thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_5thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_5thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_5thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_6thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_6thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_6thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_6thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_6thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_6thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_6thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_6thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_6thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_6thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_6thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_6thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_6thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_6thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_6thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_6thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_6thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_6thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_7thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_7thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_7thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_7thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_7thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_7thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_7thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_7thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_7thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_7thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_7thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_7thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_7thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_7thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_7thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_7thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_7thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_7thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_8thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_8thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_8thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_8thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_8thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_8thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_8thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_8thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_8thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_8thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_8thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_8thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_8thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_8thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_8thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_8thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_8thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_8thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_9thMux_g1				(0x0)
#define PARAMSET_ROIC_0_R1_9thMux_g2				(0x0)
#define PARAMSET_ROIC_0_R1_9thMux_g3				(0x0)
#define PARAMSET_ROIC_1_R1_9thMux_g1				(0x0)
#define PARAMSET_ROIC_1_R1_9thMux_g2				(0x0)
#define PARAMSET_ROIC_1_R1_9thMux_g3				(0x0)
#define PARAMSET_ROIC_2_R1_9thMux_g1				(0x0)
#define PARAMSET_ROIC_2_R1_9thMux_g2				(0x0)
#define PARAMSET_ROIC_2_R1_9thMux_g3				(0x0)
#define PARAMSET_ROIC_3_R1_9thMux_g1				(0x0)
#define PARAMSET_ROIC_3_R1_9thMux_g2				(0x0)
#define PARAMSET_ROIC_3_R1_9thMux_g3				(0x0)
#define PARAMSET_ROIC_4_R1_9thMux_g1				(0x0)
#define PARAMSET_ROIC_4_R1_9thMux_g2				(0x0)
#define PARAMSET_ROIC_4_R1_9thMux_g3				(0x0)
#define PARAMSET_ROIC_5_R1_9thMux_g1				(0x0)
#define PARAMSET_ROIC_5_R1_9thMux_g2				(0x0)
#define PARAMSET_ROIC_5_R1_9thMux_g3				(0x0)

#define PARAMSET_ROIC_0_R1_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_0_R1_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_1_R1_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_2_R1_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_3_R1_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_4_R1_LastMux_Bottom_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Top_Line_g1				(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Top_Line_g2				(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Top_Line_g3				(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Middle_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Middle_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Middle_Line_g3			(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Bottom_Line_g1			(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Bottom_Line_g2			(0x0)
#define PARAMSET_ROIC_5_R1_LastMux_Bottom_Line_g3			(0x0)

#else /* USED_RAWDATA_TUNE_CALIBRATION */
	#define PARAMSET_ROIC_0_R0_1stMux_Top_Line_g1	(16)
	#define PARAMSET_ROIC_0_R0_1stMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_0_R0_1stMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_0_R0_1stMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_0_R0_1stMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_0_R0_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_0_R0_1stMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_0_R0_1stMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_0_R0_1stMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_1_R0_1stMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_1_R0_1stMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_1_R0_1stMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_1_R0_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_1_R0_1stMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_1_R0_1stMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_1_R0_1stMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_1_R0_1stMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_1_R0_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_2_R0_1stMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_2_R0_1stMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_2_R0_1stMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_2_R0_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_2_R0_1stMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_2_R0_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_2_R0_1stMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_2_R0_1stMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_2_R0_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_3_R0_1stMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_3_R0_1stMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_3_R0_1stMux_Top_Line_g3	(19)
	#define PARAMSET_ROIC_3_R0_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_3_R0_1stMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_3_R0_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_3_R0_1stMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_3_R0_1stMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_3_R0_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_4_R0_1stMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_4_R0_1stMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_4_R0_1stMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_4_R0_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_4_R0_1stMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_4_R0_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_4_R0_1stMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_4_R0_1stMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_4_R0_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_5_R0_1stMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_5_R0_1stMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_5_R0_1stMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_5_R0_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_5_R0_1stMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_5_R0_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_5_R0_1stMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_5_R0_1stMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_5_R0_1stMux_Bottom_Line_g3	(18)

	#define PARAMSET_ROIC_0_R0_2ndMux_g1	(17)
	#define PARAMSET_ROIC_0_R0_2ndMux_g2	(18)
	#define PARAMSET_ROIC_0_R0_2ndMux_g3	(18)
	#define PARAMSET_ROIC_1_R0_2ndMux_g1	(18)
	#define PARAMSET_ROIC_1_R0_2ndMux_g2	(18)
	#define PARAMSET_ROIC_1_R0_2ndMux_g3	(18)
	#define PARAMSET_ROIC_2_R0_2ndMux_g1	(17)
	#define PARAMSET_ROIC_2_R0_2ndMux_g2	(17)
	#define PARAMSET_ROIC_2_R0_2ndMux_g3	(18)
	#define PARAMSET_ROIC_3_R0_2ndMux_g1	(18)
	#define PARAMSET_ROIC_3_R0_2ndMux_g2	(18)
	#define PARAMSET_ROIC_3_R0_2ndMux_g3	(18)
	#define PARAMSET_ROIC_4_R0_2ndMux_g1	(18)
	#define PARAMSET_ROIC_4_R0_2ndMux_g2	(18)
	#define PARAMSET_ROIC_4_R0_2ndMux_g3	(18)
	#define PARAMSET_ROIC_5_R0_2ndMux_g1	(18)
	#define PARAMSET_ROIC_5_R0_2ndMux_g2	(18)
	#define PARAMSET_ROIC_5_R0_2ndMux_g3	(18)

	#define PARAMSET_ROIC_0_R0_3rdMux_g1	(17)
	#define PARAMSET_ROIC_0_R0_3rdMux_g2	(18)
	#define PARAMSET_ROIC_0_R0_3rdMux_g3	(18)
	#define PARAMSET_ROIC_1_R0_3rdMux_g1	(18)
	#define PARAMSET_ROIC_1_R0_3rdMux_g2	(18)
	#define PARAMSET_ROIC_1_R0_3rdMux_g3	(18)
	#define PARAMSET_ROIC_2_R0_3rdMux_g1	(17)
	#define PARAMSET_ROIC_2_R0_3rdMux_g2	(17)
	#define PARAMSET_ROIC_2_R0_3rdMux_g3	(18)
	#define PARAMSET_ROIC_3_R0_3rdMux_g1	(18)
	#define PARAMSET_ROIC_3_R0_3rdMux_g2	(18)
	#define PARAMSET_ROIC_3_R0_3rdMux_g3	(18)
	#define PARAMSET_ROIC_4_R0_3rdMux_g1	(18)
	#define PARAMSET_ROIC_4_R0_3rdMux_g2	(18)
	#define PARAMSET_ROIC_4_R0_3rdMux_g3	(18)
	#define PARAMSET_ROIC_5_R0_3rdMux_g1	(18)
	#define PARAMSET_ROIC_5_R0_3rdMux_g2	(18)
	#define PARAMSET_ROIC_5_R0_3rdMux_g3	(18)

	#define PARAMSET_ROIC_0_R0_4thMux_g1	(17)
	#define PARAMSET_ROIC_0_R0_4thMux_g2	(18)
	#define PARAMSET_ROIC_0_R0_4thMux_g3	(18)
	#define PARAMSET_ROIC_1_R0_4thMux_g1	(18)
	#define PARAMSET_ROIC_1_R0_4thMux_g2	(18)
	#define PARAMSET_ROIC_1_R0_4thMux_g3	(18)
	#define PARAMSET_ROIC_2_R0_4thMux_g1	(17)
	#define PARAMSET_ROIC_2_R0_4thMux_g2	(18)
	#define PARAMSET_ROIC_2_R0_4thMux_g3	(18)
	#define PARAMSET_ROIC_3_R0_4thMux_g1	(18)
	#define PARAMSET_ROIC_3_R0_4thMux_g2	(18)
	#define PARAMSET_ROIC_3_R0_4thMux_g3	(18)
	#define PARAMSET_ROIC_4_R0_4thMux_g1	(18)
	#define PARAMSET_ROIC_4_R0_4thMux_g2	(18)
	#define PARAMSET_ROIC_4_R0_4thMux_g3	(18)
	#define PARAMSET_ROIC_5_R0_4thMux_g1	(18)
	#define PARAMSET_ROIC_5_R0_4thMux_g2	(18)
	#define PARAMSET_ROIC_5_R0_4thMux_g3	(18)

	#define PARAMSET_ROIC_0_R0_5thMux_g1	(17)
	#define PARAMSET_ROIC_0_R0_5thMux_g2	(18)
	#define PARAMSET_ROIC_0_R0_5thMux_g3	(17)
	#define PARAMSET_ROIC_1_R0_5thMux_g1	(18)
	#define PARAMSET_ROIC_1_R0_5thMux_g2	(18)
	#define PARAMSET_ROIC_1_R0_5thMux_g3	(18)
	#define PARAMSET_ROIC_2_R0_5thMux_g1	(17)
	#define PARAMSET_ROIC_2_R0_5thMux_g2	(17)
	#define PARAMSET_ROIC_2_R0_5thMux_g3	(18)
	#define PARAMSET_ROIC_3_R0_5thMux_g1	(18)
	#define PARAMSET_ROIC_3_R0_5thMux_g2	(18)
	#define PARAMSET_ROIC_3_R0_5thMux_g3	(18)
	#define PARAMSET_ROIC_4_R0_5thMux_g1	(18)
	#define PARAMSET_ROIC_4_R0_5thMux_g2	(18)
	#define PARAMSET_ROIC_4_R0_5thMux_g3	(18)
	#define PARAMSET_ROIC_5_R0_5thMux_g1	(18)
	#define PARAMSET_ROIC_5_R0_5thMux_g2	(18)
	#define PARAMSET_ROIC_5_R0_5thMux_g3	(18)

	#define PARAMSET_ROIC_0_R0_6thMux_g1	(0)
	#define PARAMSET_ROIC_0_R0_6thMux_g2	(0)
	#define PARAMSET_ROIC_0_R0_6thMux_g3	(0)
	#define PARAMSET_ROIC_1_R0_6thMux_g1	(0)
	#define PARAMSET_ROIC_1_R0_6thMux_g2	(0)
	#define PARAMSET_ROIC_1_R0_6thMux_g3	(0)
	#define PARAMSET_ROIC_2_R0_6thMux_g1	(0)
	#define PARAMSET_ROIC_2_R0_6thMux_g2	(0)
	#define PARAMSET_ROIC_2_R0_6thMux_g3	(0)
	#define PARAMSET_ROIC_3_R0_6thMux_g1	(0)
	#define PARAMSET_ROIC_3_R0_6thMux_g2	(0)
	#define PARAMSET_ROIC_3_R0_6thMux_g3	(0)
	#define PARAMSET_ROIC_4_R0_6thMux_g1	(0)
	#define PARAMSET_ROIC_4_R0_6thMux_g2	(0)
	#define PARAMSET_ROIC_4_R0_6thMux_g3	(0)
	#define PARAMSET_ROIC_5_R0_6thMux_g1	(0)
	#define PARAMSET_ROIC_5_R0_6thMux_g2	(0)
	#define PARAMSET_ROIC_5_R0_6thMux_g3	(0)

	#define PARAMSET_ROIC_0_R0_7thMux_g1	(0)
	#define PARAMSET_ROIC_0_R0_7thMux_g2	(0)
	#define PARAMSET_ROIC_0_R0_7thMux_g3	(0)
	#define PARAMSET_ROIC_1_R0_7thMux_g1	(0)
	#define PARAMSET_ROIC_1_R0_7thMux_g2	(0)
	#define PARAMSET_ROIC_1_R0_7thMux_g3	(0)
	#define PARAMSET_ROIC_2_R0_7thMux_g1	(0)
	#define PARAMSET_ROIC_2_R0_7thMux_g2	(0)
	#define PARAMSET_ROIC_2_R0_7thMux_g3	(0)
	#define PARAMSET_ROIC_3_R0_7thMux_g1	(0)
	#define PARAMSET_ROIC_3_R0_7thMux_g2	(0)
	#define PARAMSET_ROIC_3_R0_7thMux_g3	(0)
	#define PARAMSET_ROIC_4_R0_7thMux_g1	(0)
	#define PARAMSET_ROIC_4_R0_7thMux_g2	(0)
	#define PARAMSET_ROIC_4_R0_7thMux_g3	(0)
	#define PARAMSET_ROIC_5_R0_7thMux_g1	(0)
	#define PARAMSET_ROIC_5_R0_7thMux_g2	(0)
	#define PARAMSET_ROIC_5_R0_7thMux_g3	(0)

	#define PARAMSET_ROIC_0_R0_8thMux_g1	(0)
	#define PARAMSET_ROIC_0_R0_8thMux_g2	(0)
	#define PARAMSET_ROIC_0_R0_8thMux_g3	(0)
	#define PARAMSET_ROIC_1_R0_8thMux_g1	(0)
	#define PARAMSET_ROIC_1_R0_8thMux_g2	(0)
	#define PARAMSET_ROIC_1_R0_8thMux_g3	(0)
	#define PARAMSET_ROIC_2_R0_8thMux_g1	(0)
	#define PARAMSET_ROIC_2_R0_8thMux_g2	(0)
	#define PARAMSET_ROIC_2_R0_8thMux_g3	(0)
	#define PARAMSET_ROIC_3_R0_8thMux_g1	(0)
	#define PARAMSET_ROIC_3_R0_8thMux_g2	(0)
	#define PARAMSET_ROIC_3_R0_8thMux_g3	(0)
	#define PARAMSET_ROIC_4_R0_8thMux_g1	(0)
	#define PARAMSET_ROIC_4_R0_8thMux_g2	(0)
	#define PARAMSET_ROIC_4_R0_8thMux_g3	(0)
	#define PARAMSET_ROIC_5_R0_8thMux_g1	(0)
	#define PARAMSET_ROIC_5_R0_8thMux_g2	(0)
	#define PARAMSET_ROIC_5_R0_8thMux_g3	(0)

	#define PARAMSET_ROIC_0_R0_9thMux_g1	(0)
	#define PARAMSET_ROIC_0_R0_9thMux_g2	(0)
	#define PARAMSET_ROIC_0_R0_9thMux_g3	(0)
	#define PARAMSET_ROIC_1_R0_9thMux_g1	(0)
	#define PARAMSET_ROIC_1_R0_9thMux_g2	(0)
	#define PARAMSET_ROIC_1_R0_9thMux_g3	(0)
	#define PARAMSET_ROIC_2_R0_9thMux_g1	(0)
	#define PARAMSET_ROIC_2_R0_9thMux_g2	(0)
	#define PARAMSET_ROIC_2_R0_9thMux_g3	(0)
	#define PARAMSET_ROIC_3_R0_9thMux_g1	(0)
	#define PARAMSET_ROIC_3_R0_9thMux_g2	(0)
	#define PARAMSET_ROIC_3_R0_9thMux_g3	(0)
	#define PARAMSET_ROIC_4_R0_9thMux_g1	(0)
	#define PARAMSET_ROIC_4_R0_9thMux_g2	(0)
	#define PARAMSET_ROIC_4_R0_9thMux_g3	(0)
	#define PARAMSET_ROIC_5_R0_9thMux_g1	(0)
	#define PARAMSET_ROIC_5_R0_9thMux_g2	(0)
	#define PARAMSET_ROIC_5_R0_9thMux_g3	(0)

	#define PARAMSET_ROIC_0_R0_LastMux_Top_Line_g1	(16)
	#define PARAMSET_ROIC_0_R0_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_0_R0_LastMux_Top_Line_g3	(17)
	#define PARAMSET_ROIC_0_R0_LastMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_0_R0_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_0_R0_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_0_R0_LastMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_0_R0_LastMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_0_R0_LastMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_1_R0_LastMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_1_R0_LastMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_1_R0_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_1_R0_LastMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_1_R0_LastMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_1_R0_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_1_R0_LastMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_1_R0_LastMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_1_R0_LastMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_2_R0_LastMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_2_R0_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_2_R0_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_2_R0_LastMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_2_R0_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_2_R0_LastMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_2_R0_LastMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_2_R0_LastMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_2_R0_LastMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_3_R0_LastMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_3_R0_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_3_R0_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_3_R0_LastMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_3_R0_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_3_R0_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_3_R0_LastMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_3_R0_LastMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_3_R0_LastMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_4_R0_LastMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_4_R0_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_4_R0_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_4_R0_LastMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_4_R0_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_4_R0_LastMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_4_R0_LastMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_4_R0_LastMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_4_R0_LastMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_5_R0_LastMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_5_R0_LastMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_5_R0_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_5_R0_LastMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_5_R0_LastMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_5_R0_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_5_R0_LastMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_5_R0_LastMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_5_R0_LastMux_Bottom_Line_g3	(16)

	#define PARAMSET_ROIC_0_R1_1stMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_0_R1_1stMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_0_R1_1stMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_0_R1_1stMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_0_R1_1stMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_0_R1_1stMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_0_R1_1stMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_0_R1_1stMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_0_R1_1stMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_1_R1_1stMux_Top_Line_g1	(16)
	#define PARAMSET_ROIC_1_R1_1stMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_1_R1_1stMux_Top_Line_g3	(19)
	#define PARAMSET_ROIC_1_R1_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_1_R1_1stMux_Middle_Line_g2	(19)
	#define PARAMSET_ROIC_1_R1_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_1_R1_1stMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_1_R1_1stMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_1_R1_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_2_R1_1stMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_2_R1_1stMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_2_R1_1stMux_Top_Line_g3	(19)
	#define PARAMSET_ROIC_2_R1_1stMux_Middle_Line_g1	(19)
	#define PARAMSET_ROIC_2_R1_1stMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_2_R1_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_2_R1_1stMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_2_R1_1stMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_2_R1_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_3_R1_1stMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_3_R1_1stMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_3_R1_1stMux_Top_Line_g3	(17)
	#define PARAMSET_ROIC_3_R1_1stMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_3_R1_1stMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_3_R1_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_3_R1_1stMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_3_R1_1stMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_3_R1_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_4_R1_1stMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_4_R1_1stMux_Top_Line_g2	(16)
	#define PARAMSET_ROIC_4_R1_1stMux_Top_Line_g3	(19)
	#define PARAMSET_ROIC_4_R1_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_4_R1_1stMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_4_R1_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_4_R1_1stMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_4_R1_1stMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_4_R1_1stMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_5_R1_1stMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_5_R1_1stMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_5_R1_1stMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_5_R1_1stMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_5_R1_1stMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_5_R1_1stMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_5_R1_1stMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_5_R1_1stMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_5_R1_1stMux_Bottom_Line_g3	(17)

	#define PARAMSET_ROIC_0_R1_2ndMux_g1	(17)
	#define PARAMSET_ROIC_0_R1_2ndMux_g2	(17)
	#define PARAMSET_ROIC_0_R1_2ndMux_g3	(17)
	#define PARAMSET_ROIC_1_R1_2ndMux_g1	(18)
	#define PARAMSET_ROIC_1_R1_2ndMux_g2	(18)
	#define PARAMSET_ROIC_1_R1_2ndMux_g3	(18)
	#define PARAMSET_ROIC_2_R1_2ndMux_g1	(18)
	#define PARAMSET_ROIC_2_R1_2ndMux_g2	(18)
	#define PARAMSET_ROIC_2_R1_2ndMux_g3	(18)
	#define PARAMSET_ROIC_3_R1_2ndMux_g1	(18)
	#define PARAMSET_ROIC_3_R1_2ndMux_g2	(18)
	#define PARAMSET_ROIC_3_R1_2ndMux_g3	(18)
	#define PARAMSET_ROIC_4_R1_2ndMux_g1	(18)
	#define PARAMSET_ROIC_4_R1_2ndMux_g2	(18)
	#define PARAMSET_ROIC_4_R1_2ndMux_g3	(18)
	#define PARAMSET_ROIC_5_R1_2ndMux_g1	(17)
	#define PARAMSET_ROIC_5_R1_2ndMux_g2	(17)
	#define PARAMSET_ROIC_5_R1_2ndMux_g3	(17)

	#define PARAMSET_ROIC_0_R1_3rdMux_g1	(17)
	#define PARAMSET_ROIC_0_R1_3rdMux_g2	(17)
	#define PARAMSET_ROIC_0_R1_3rdMux_g3	(17)
	#define PARAMSET_ROIC_1_R1_3rdMux_g1	(18)
	#define PARAMSET_ROIC_1_R1_3rdMux_g2	(18)
	#define PARAMSET_ROIC_1_R1_3rdMux_g3	(18)
	#define PARAMSET_ROIC_2_R1_3rdMux_g1	(18)
	#define PARAMSET_ROIC_2_R1_3rdMux_g2	(18)
	#define PARAMSET_ROIC_2_R1_3rdMux_g3	(18)
	#define PARAMSET_ROIC_3_R1_3rdMux_g1	(18)
	#define PARAMSET_ROIC_3_R1_3rdMux_g2	(18)
	#define PARAMSET_ROIC_3_R1_3rdMux_g3	(18)
	#define PARAMSET_ROIC_4_R1_3rdMux_g1	(18)
	#define PARAMSET_ROIC_4_R1_3rdMux_g2	(18)
	#define PARAMSET_ROIC_4_R1_3rdMux_g3	(18)
	#define PARAMSET_ROIC_5_R1_3rdMux_g1	(17)
	#define PARAMSET_ROIC_5_R1_3rdMux_g2	(17)
	#define PARAMSET_ROIC_5_R1_3rdMux_g3	(17)

	#define PARAMSET_ROIC_0_R1_4thMux_g1	(17)
	#define PARAMSET_ROIC_0_R1_4thMux_g2	(17)
	#define PARAMSET_ROIC_0_R1_4thMux_g3	(17)
	#define PARAMSET_ROIC_1_R1_4thMux_g1	(18)
	#define PARAMSET_ROIC_1_R1_4thMux_g2	(18)
	#define PARAMSET_ROIC_1_R1_4thMux_g3	(18)
	#define PARAMSET_ROIC_2_R1_4thMux_g1	(18)
	#define PARAMSET_ROIC_2_R1_4thMux_g2	(18)
	#define PARAMSET_ROIC_2_R1_4thMux_g3	(18)
	#define PARAMSET_ROIC_3_R1_4thMux_g1	(18)
	#define PARAMSET_ROIC_3_R1_4thMux_g2	(18)
	#define PARAMSET_ROIC_3_R1_4thMux_g3	(18)
	#define PARAMSET_ROIC_4_R1_4thMux_g1	(18)
	#define PARAMSET_ROIC_4_R1_4thMux_g2	(18)
	#define PARAMSET_ROIC_4_R1_4thMux_g3	(18)
	#define PARAMSET_ROIC_5_R1_4thMux_g1	(17)
	#define PARAMSET_ROIC_5_R1_4thMux_g2	(17)
	#define PARAMSET_ROIC_5_R1_4thMux_g3	(17)

	#define PARAMSET_ROIC_0_R1_5thMux_g1	(17)
	#define PARAMSET_ROIC_0_R1_5thMux_g2	(17)
	#define PARAMSET_ROIC_0_R1_5thMux_g3	(17)
	#define PARAMSET_ROIC_1_R1_5thMux_g1	(18)
	#define PARAMSET_ROIC_1_R1_5thMux_g2	(18)
	#define PARAMSET_ROIC_1_R1_5thMux_g3	(18)
	#define PARAMSET_ROIC_2_R1_5thMux_g1	(18)
	#define PARAMSET_ROIC_2_R1_5thMux_g2	(18)
	#define PARAMSET_ROIC_2_R1_5thMux_g3	(18)
	#define PARAMSET_ROIC_3_R1_5thMux_g1	(18)
	#define PARAMSET_ROIC_3_R1_5thMux_g2	(18)
	#define PARAMSET_ROIC_3_R1_5thMux_g3	(18)
	#define PARAMSET_ROIC_4_R1_5thMux_g1	(18)
	#define PARAMSET_ROIC_4_R1_5thMux_g2	(18)
	#define PARAMSET_ROIC_4_R1_5thMux_g3	(18)
	#define PARAMSET_ROIC_5_R1_5thMux_g1	(17)
	#define PARAMSET_ROIC_5_R1_5thMux_g2	(17)
	#define PARAMSET_ROIC_5_R1_5thMux_g3	(17)

	#define PARAMSET_ROIC_0_R1_6thMux_g1	(0)
	#define PARAMSET_ROIC_0_R1_6thMux_g2	(0)
	#define PARAMSET_ROIC_0_R1_6thMux_g3	(0)
	#define PARAMSET_ROIC_1_R1_6thMux_g1	(0)
	#define PARAMSET_ROIC_1_R1_6thMux_g2	(0)
	#define PARAMSET_ROIC_1_R1_6thMux_g3	(0)
	#define PARAMSET_ROIC_2_R1_6thMux_g1	(0)
	#define PARAMSET_ROIC_2_R1_6thMux_g2	(0)
	#define PARAMSET_ROIC_2_R1_6thMux_g3	(0)
	#define PARAMSET_ROIC_3_R1_6thMux_g1	(0)
	#define PARAMSET_ROIC_3_R1_6thMux_g2	(0)
	#define PARAMSET_ROIC_3_R1_6thMux_g3	(0)
	#define PARAMSET_ROIC_4_R1_6thMux_g1	(0)
	#define PARAMSET_ROIC_4_R1_6thMux_g2	(0)
	#define PARAMSET_ROIC_4_R1_6thMux_g3	(0)
	#define PARAMSET_ROIC_5_R1_6thMux_g1	(0)
	#define PARAMSET_ROIC_5_R1_6thMux_g2	(0)
	#define PARAMSET_ROIC_5_R1_6thMux_g3	(0)

	#define PARAMSET_ROIC_0_R1_7thMux_g1	(0)
	#define PARAMSET_ROIC_0_R1_7thMux_g2	(0)
	#define PARAMSET_ROIC_0_R1_7thMux_g3	(0)
	#define PARAMSET_ROIC_1_R1_7thMux_g1	(0)
	#define PARAMSET_ROIC_1_R1_7thMux_g2	(0)
	#define PARAMSET_ROIC_1_R1_7thMux_g3	(0)
	#define PARAMSET_ROIC_2_R1_7thMux_g1	(0)
	#define PARAMSET_ROIC_2_R1_7thMux_g2	(0)
	#define PARAMSET_ROIC_2_R1_7thMux_g3	(0)
	#define PARAMSET_ROIC_3_R1_7thMux_g1	(0)
	#define PARAMSET_ROIC_3_R1_7thMux_g2	(0)
	#define PARAMSET_ROIC_3_R1_7thMux_g3	(0)
	#define PARAMSET_ROIC_4_R1_7thMux_g1	(0)
	#define PARAMSET_ROIC_4_R1_7thMux_g2	(0)
	#define PARAMSET_ROIC_4_R1_7thMux_g3	(0)
	#define PARAMSET_ROIC_5_R1_7thMux_g1	(0)
	#define PARAMSET_ROIC_5_R1_7thMux_g2	(0)
	#define PARAMSET_ROIC_5_R1_7thMux_g3	(0)

	#define PARAMSET_ROIC_0_R1_8thMux_g1	(0)
	#define PARAMSET_ROIC_0_R1_8thMux_g2	(0)
	#define PARAMSET_ROIC_0_R1_8thMux_g3	(0)
	#define PARAMSET_ROIC_1_R1_8thMux_g1	(0)
	#define PARAMSET_ROIC_1_R1_8thMux_g2	(0)
	#define PARAMSET_ROIC_1_R1_8thMux_g3	(0)
	#define PARAMSET_ROIC_2_R1_8thMux_g1	(0)
	#define PARAMSET_ROIC_2_R1_8thMux_g2	(0)
	#define PARAMSET_ROIC_2_R1_8thMux_g3	(0)
	#define PARAMSET_ROIC_3_R1_8thMux_g1	(0)
	#define PARAMSET_ROIC_3_R1_8thMux_g2	(0)
	#define PARAMSET_ROIC_3_R1_8thMux_g3	(0)
	#define PARAMSET_ROIC_4_R1_8thMux_g1	(0)
	#define PARAMSET_ROIC_4_R1_8thMux_g2	(0)
	#define PARAMSET_ROIC_4_R1_8thMux_g3	(0)
	#define PARAMSET_ROIC_5_R1_8thMux_g1	(0)
	#define PARAMSET_ROIC_5_R1_8thMux_g2	(0)
	#define PARAMSET_ROIC_5_R1_8thMux_g3	(0)

	#define PARAMSET_ROIC_0_R1_9thMux_g1	(0)
	#define PARAMSET_ROIC_0_R1_9thMux_g2	(0)
	#define PARAMSET_ROIC_0_R1_9thMux_g3	(0)
	#define PARAMSET_ROIC_1_R1_9thMux_g1	(0)
	#define PARAMSET_ROIC_1_R1_9thMux_g2	(0)
	#define PARAMSET_ROIC_1_R1_9thMux_g3	(0)
	#define PARAMSET_ROIC_2_R1_9thMux_g1	(0)
	#define PARAMSET_ROIC_2_R1_9thMux_g2	(0)
	#define PARAMSET_ROIC_2_R1_9thMux_g3	(0)
	#define PARAMSET_ROIC_3_R1_9thMux_g1	(0)
	#define PARAMSET_ROIC_3_R1_9thMux_g2	(0)
	#define PARAMSET_ROIC_3_R1_9thMux_g3	(0)
	#define PARAMSET_ROIC_4_R1_9thMux_g1	(0)
	#define PARAMSET_ROIC_4_R1_9thMux_g2	(0)
	#define PARAMSET_ROIC_4_R1_9thMux_g3	(0)
	#define PARAMSET_ROIC_5_R1_9thMux_g1	(0)
	#define PARAMSET_ROIC_5_R1_9thMux_g2	(0)
	#define PARAMSET_ROIC_5_R1_9thMux_g3	(0)

	#define PARAMSET_ROIC_0_R1_LastMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_0_R1_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_0_R1_LastMux_Top_Line_g3	(17)
	#define PARAMSET_ROIC_0_R1_LastMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_0_R1_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_0_R1_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_0_R1_LastMux_Bottom_Line_g1	(16)
	#define PARAMSET_ROIC_0_R1_LastMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_0_R1_LastMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_1_R1_LastMux_Top_Line_g1	(15)
	#define PARAMSET_ROIC_1_R1_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_1_R1_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_1_R1_LastMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_1_R1_LastMux_Middle_Line_g2	(18)
	#define PARAMSET_ROIC_1_R1_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_1_R1_LastMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_1_R1_LastMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_1_R1_LastMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_2_R1_LastMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_2_R1_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_2_R1_LastMux_Top_Line_g3	(19)
	#define PARAMSET_ROIC_2_R1_LastMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_2_R1_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_2_R1_LastMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_2_R1_LastMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_2_R1_LastMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_2_R1_LastMux_Bottom_Line_g3	(17)
	#define PARAMSET_ROIC_3_R1_LastMux_Top_Line_g1	(18)
	#define PARAMSET_ROIC_3_R1_LastMux_Top_Line_g2	(18)
	#define PARAMSET_ROIC_3_R1_LastMux_Top_Line_g3	(17)
	#define PARAMSET_ROIC_3_R1_LastMux_Middle_Line_g1	(17)
	#define PARAMSET_ROIC_3_R1_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_3_R1_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_3_R1_LastMux_Bottom_Line_g1	(18)
	#define PARAMSET_ROIC_3_R1_LastMux_Bottom_Line_g2	(18)
	#define PARAMSET_ROIC_3_R1_LastMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_4_R1_LastMux_Top_Line_g1	(17)
	#define PARAMSET_ROIC_4_R1_LastMux_Top_Line_g2	(16)
	#define PARAMSET_ROIC_4_R1_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_4_R1_LastMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_4_R1_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_4_R1_LastMux_Middle_Line_g3	(18)
	#define PARAMSET_ROIC_4_R1_LastMux_Bottom_Line_g1	(17)
	#define PARAMSET_ROIC_4_R1_LastMux_Bottom_Line_g2	(17)
	#define PARAMSET_ROIC_4_R1_LastMux_Bottom_Line_g3	(18)
	#define PARAMSET_ROIC_5_R1_LastMux_Top_Line_g1	(16)
	#define PARAMSET_ROIC_5_R1_LastMux_Top_Line_g2	(17)
	#define PARAMSET_ROIC_5_R1_LastMux_Top_Line_g3	(18)
	#define PARAMSET_ROIC_5_R1_LastMux_Middle_Line_g1	(18)
	#define PARAMSET_ROIC_5_R1_LastMux_Middle_Line_g2	(17)
	#define PARAMSET_ROIC_5_R1_LastMux_Middle_Line_g3	(17)
	#define PARAMSET_ROIC_5_R1_LastMux_Bottom_Line_g1	(16)
	#define PARAMSET_ROIC_5_R1_LastMux_Bottom_Line_g2	(16)
	#define PARAMSET_ROIC_5_R1_LastMux_Bottom_Line_g3	(16)

#endif /* USED_RAWDATA_TUNE_CALIBRATION */

#if USED_LOCAL_IDLE_MODE_CONTROL
	#define PARAMSET_IDLE_ROIC_0_R0_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_0_R0_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_0_R0_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_1_R0_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_1_R0_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_1_R0_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_2_R0_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_2_R0_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_2_R0_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_3_R0_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_3_R0_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_3_R0_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_4_R0_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_4_R0_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_4_R0_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_5_R0_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_5_R0_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_5_R0_CR_GTUNE_PenData_Global_Tune	(0)

	#define PARAMSET_IDLE_ROIC_0_R1_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_0_R1_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_0_R1_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_1_R1_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_1_R1_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_1_R1_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_2_R1_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_2_R1_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_2_R1_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_3_R1_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_3_R1_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_3_R1_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_4_R1_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_4_R1_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_4_R1_CR_GTUNE_PenData_Global_Tune	(0)
	#define PARAMSET_IDLE_ROIC_5_R1_CR_GTUNE_Finger_Global_Tune		(2)
	#define PARAMSET_IDLE_ROIC_5_R1_CR_GTUNE_PenPos_Global_Tune		(0)
	#define PARAMSET_IDLE_ROIC_5_R1_CR_GTUNE_PenData_Global_Tune	(0)


	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Top_Line_g1				(10)//(25)//(24)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Top_Line_g2				(10)//(9)//(10)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Top_Line_g3				(10)//(1)//(0)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Middle_Line_g1			(10)//(24)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Middle_Line_g2			(10)//(5)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Middle_Line_g3			(10)//(1)//(0)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Bottom_Line_g1			(10)//(18)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Bottom_Line_g2			(10)//(5)
	#define PARAMSET_IDLE_ROIC_0_R0_1stMux_Bottom_Line_g3			(10)//(0)

	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Top_Line_g1				(10)//(16)//(14)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Top_Line_g2				(10)//(7)//(10)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Top_Line_g3				(10)//(0)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Middle_Line_g1			(10)//(10)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Middle_Line_g2			(10)//(7)//(10)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Middle_Line_g3			(10)//(0)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Bottom_Line_g1			(10)//(12)//(11)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Bottom_Line_g2			(10)//(0)//(1)
	#define PARAMSET_IDLE_ROIC_1_R0_1stMux_Bottom_Line_g3			(10)//(0)

	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Top_Line_g1				(10)//(21)//(22)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Top_Line_g2				(10)//(8)//(10)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Top_Line_g3				(10)//(2)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Middle_Line_g1			(10)//(11)//(8)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Middle_Line_g2			(10)//(4)//(5)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Middle_Line_g3			(10)//(0)//(2)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Bottom_Line_g1			(10)//(12)//(5)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Bottom_Line_g2			(10)//(5)//(3)
	#define PARAMSET_IDLE_ROIC_2_R0_1stMux_Bottom_Line_g3			(10)//(0)//(2)

	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Top_Line_g1				(10)//(15)//(16)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Top_Line_g2				(10)//(7)//(10)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Top_Line_g3				(10)//(0)//(5)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Middle_Line_g1			(10)//(14)//(16)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Middle_Line_g2			(10)//(11)//(15)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Middle_Line_g3			(10)//(9)//(15)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Bottom_Line_g1			(10)//(20)//(23)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Bottom_Line_g2			(10)//(4)//(6)
	#define PARAMSET_IDLE_ROIC_3_R0_1stMux_Bottom_Line_g3			(10)//(2)//(6)

	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Top_Line_g1				(10)//(16)//(13)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Top_Line_g2				(10)//(10)//(13)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Top_Line_g3				(10)//(3)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Middle_Line_g1			(10)//(13)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Middle_Line_g2			(10)//(10)//(13)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Middle_Line_g3			(10)//(7)//(8)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Bottom_Line_g1			(10)//(13)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Bottom_Line_g2			(10)//(10)//(13)
	#define PARAMSET_IDLE_ROIC_4_R0_1stMux_Bottom_Line_g3			(10)//(4)//(8)

	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Top_Line_g1				(10)//(10)//(13)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Top_Line_g2				(10)//(8)//(10)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Top_Line_g3				(10)//(0)//(2)//(3)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Middle_Line_g1			(10)//(11)//(12)//(13)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Middle_Line_g2			(10)//(2)//(5)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Middle_Line_g3			(10)//(0)//(1)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Bottom_Line_g1			(10)//(11)//(13)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Bottom_Line_g2			(10)//(2)//(5)
	#define PARAMSET_IDLE_ROIC_5_R0_1stMux_Bottom_Line_g3			(10)//(0)


	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Top_Line_g1				(10)//(6)//(0)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Top_Line_g2				(10)//(0)//(0)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Top_Line_g3				(10)//(0)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Middle_Line_g1			(10)//(7)//(6)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Middle_Line_g2			(10)//(1)//(0)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Middle_Line_g3			(10)//(0)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Bottom_Line_g1			(10)//(6)//(0)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Bottom_Line_g2			(10)//(1)//(0)
	#define PARAMSET_IDLE_ROIC_0_R1_1stMux_Bottom_Line_g3			(10)//(0)

	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Top_Line_g1				(10)//(7)//(10)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Top_Line_g2				(10)//(1)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Top_Line_g3				(10)//(1)//(0)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Middle_Line_g1			(10)//(7)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Middle_Line_g2			(10)//(5)//(4)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Middle_Line_g3			(10)//(0)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Bottom_Line_g1			(10)//(7)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Bottom_Line_g2			(10)//(4)
	#define PARAMSET_IDLE_ROIC_1_R1_1stMux_Bottom_Line_g3			(10)//(0)

	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Top_Line_g1				(10)//(15)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Top_Line_g2				(10)//(8)//(10)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Top_Line_g3				(10)//(0)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Middle_Line_g1			(10)//(13)//(15)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Middle_Line_g2			(10)//(8)//(10)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Middle_Line_g3			(10)//(2)//(7)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Bottom_Line_g1			(10)//(13)//(15)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Bottom_Line_g2			(10)//(4)//(6)
	#define PARAMSET_IDLE_ROIC_2_R1_1stMux_Bottom_Line_g3			(10)//(1)//(3)

	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Top_Line_g1				(10)//(17)//(7)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Top_Line_g2				(10)//(10)//(3)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Top_Line_g3				(10)//(4)//(0)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Middle_Line_g1			(10)//(12)//(7)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Middle_Line_g2			(10)//(9)//(3)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Middle_Line_g3			(10)//(5)//(0)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Bottom_Line_g1			(10)//(12)//(7)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Bottom_Line_g2			(10)//(7)//(2)
	#define PARAMSET_IDLE_ROIC_3_R1_1stMux_Bottom_Line_g3			(10)//(2)//(0)

	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Top_Line_g1				(10)//(7)//(8)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Top_Line_g2				(10)//(7)//(10)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Top_Line_g3				(10)//(0)//(3)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Middle_Line_g1			(10)//(9)//(10)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Middle_Line_g2			(10)//(6)//(10)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Middle_Line_g3			(10)//(0)//(3)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Bottom_Line_g1			(10)//(11)//(13)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Bottom_Line_g2			(10)//(2)//(4)
	#define PARAMSET_IDLE_ROIC_4_R1_1stMux_Bottom_Line_g3			(10)//(1)

	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Top_Line_g1				(10)//(17)//(16)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Top_Line_g2				(10)//(15)//(17)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Top_Line_g3				(10)//(3)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Middle_Line_g1			(10)//(29)//(31)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Middle_Line_g2			(10)//(13)//(15)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Middle_Line_g3			(10)//(6)//(8)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Bottom_Line_g1			(10)//(28)//(31)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Bottom_Line_g2			(10)//(8)//(10)
	#define PARAMSET_IDLE_ROIC_5_R1_1stMux_Bottom_Line_g3			(10)//(2)//(3)
#endif /* USED_LOCAL_IDLE_MODE_CONTROL */


#endif /* _PARAM_CONFIGSET_ROIC_H_ */
